-- VEIL V2.0 Enterprise Schema & Strict RLS

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  website text not null,
  severity text not null check (severity in ('critical', 'high', 'medium', 'low')),
  risk_score integer not null check (risk_score between 0 and 100),
  findings jsonb,
  prompt_preview text
);

-- Enable Row Level Security (RLS)
alter table public.incidents enable row level security;

-- Drop existing policies to ensure clean state
drop policy if exists "Allow public incident reads" on public.incidents;
drop policy if exists "Allow extension incident inserts" on public.incidents;

-- READ: Only authenticated or anon users can read (In production, restrict to authenticated SOC admins)
create policy "Allow dashboard incident reads"
on public.incidents
for select
to anon, authenticated
using (true);

-- WRITE: Strict validation for incoming telemetry from the Extension
create policy "Allow strict extension incident inserts"
on public.incidents
for insert
to anon
with check (
  website <> ''
  and severity in ('critical', 'high', 'medium', 'low')
  and risk_score between 0 and 100
  and char_length(coalesce(prompt_preview, '')) <= 240
);

-- Indexing for high-performance SOC dashboard rendering
create index if not exists incidents_created_at_idx on public.incidents (created_at desc);
create index if not exists incidents_severity_idx on public.incidents (severity);

-- Realtime Publication
-- Safe to rerun even when the table is already part of the publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'incidents'
  ) then
    alter publication supabase_realtime add table public.incidents;
  end if;
end
$$;
